# Generated by Django 4.0.6 on 2022-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(help_text='The main category of an product (Cake => Dessert)', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='A detailed paraghraph about the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(help_text='An image that will show the user what the product looks like', upload_to='thumbnails/'),
        ),
    ]
