# Generated by Django 4.0.6 on 2022-08-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_views_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesSingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('categories', models.JSONField(default=[])),
            ],
        ),
    ]
